name: Ruby Conferences
url: https://rubyconferences.org
safe: true
lsi: false
source: .
exclude:
  - CNAME
  - Dangerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - Rakefile
  - data_file_validator.rb
  - notes.txt
  - vendor

plugins:
  - jekyll-feed
